### PR TITLE
Backend

### PR DESCRIPTION
**Pull request by prince-curie**
This PR contains two files.
1. logout.php this helps to end a session.
to implement it kindly create a button named log out and add a link to this file it should redirect you to the root file.
2. changeTheme.js this helps to select between light and dark theme
to use it:
a. give your change theme button an id of change-theme 
b. ensure that all-important feature in your light-theme and dark-theme.css files have an !important tag attached to it to avoid being overwritten

### CODE REVIEW

**Review by MyloCarson — COMMENTED** [review]
This is gonna cause a big problem when merged with master eventually. please, can u kindly fix all these conflicts? Thanks.

Just pull from master. Thanks

**Review by MyloCarson — CHANGES_REQUESTED** [review]
Kindly review.

**Comment by Edmund1645** [comment]
> _No description provided._

you did not set a description so there's no way to tell what this does unless combing through the files.

**Comment by prince-curie** [comment]
@MyloCarson please check for conflicts now

**Pull request merged**
